### ISSUE TITLE
Scale9Textures error 

### ISSUE THREAD

**Issue by 8power8** [cotejp/SoftKeyboard#3]
Hi 

I get an error when performing a long press on a key that contains modifiers (eg. the "a" in the AzertySwitchFr keyboard) :
```
ArgumentError: The width of the scale9Grid must be greater than zero.
	at feathers.textures::Scale9Textures()[/Users/joshtynjala/Development/Flash/feathers/source/feathers/textures/Scale9Textures.as:56]
	at view::SoftKeyboardTheme$/getScale9Image()[/path/to/my/project/src/view/SoftKeyboardTheme.as:263]
	at view::SoftKeyboardTheme/_callout()[/path/to/my/project/src/view/SoftKeyboardTheme.as:189]
```

It seems that there is an issue in the Theme class with the _callout() function that Initialize the callout  component. This function make calls to getScale9Image() function which seems to be the heart of the problem, but I can't figure out why.

I am using Feathers-2.1.1 and Starling 1.6

**Comment by cotejp** [comment]
It shouldn't call `Theme.getScale9Image()`. It should call `Theme.getImage()`. I have no clue how this got there. Corrected file have been committed. A new zip is also available on my site: http://cote.cc/projects/softkeyboard

Thanks for pointing out this problem. You are probably the first to use the French characters callout in a while... ;-)
